#!/usr/bin/env python3

import argparse

import fract


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="store_true", help="verbose mode")
    parser.add_argument("number", type=int, help="number to factorial")

    return parser.parse_args()


def main():
    args = parse_args()

    if args.verbose:
        print("Calculating factorial of {0}".format(args.number))

    print(fract.fact(args.number))


if __name__ == "__main__":
    main()
